version: '3.8'

services:
  backend:
    build: ./handyhub-backend
    container_name: handyhub-spring-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    networks:
      - handyhub-net

  frontend:
    build: ./handyhub-frontend
    container_name: handyhub-react-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - handyhub-net

networks:
  handyhub-net:
